name: Prometheus
description: Prometheus metrics
scheduling:
  type: NoDevices
spec:
  containers:
  - name: prometheus
    # View available tags here: https://hub.docker.com/r/prom/prometheus/tags
    image: prom/prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - /data/prometheus/:/prometheus
    secrets:
      - name: prometheus-config
        filepath: /etc/prometheus/prometheus.yaml
  - name: relayd
    # Note that this AMD64 image. for ARM use webhookrelay/webhookrelayd-aarch64:1
    image: webhookrelay/webhookrelayd:1
    args:
      - --mode
      - tunnel
      - -t
      - synpse-prom
    env:
      - name: RELAY_KEY
        fromSecret: relayKey
      - name: RELAY_SECRET
        fromSecret: relaySecret
    restartPolicy: {}
